### ISSUE TITLE
Move RAML api-console to dedicated repository

### ISSUE THREAD

**Issue by kiivihal** [delving/hub3#21]
Including the RAML api-console should be optional to be included in the static resources. Therefore, it is best to move it to a dedicated repository.

- remove `./ikuzo/static/api-console`
- remove `api-console` command from Makefile
- remove `ikuzo/internal/assets/filesystem_vfsdata.go`

**Comment by kiivihal** [comment]
This directory needs to be removed: '/ikuzo/static/api-console'.

**Comment by jaclu** [comment]
Done
